### ISSUE TITLE
avDropdown throws error on getSelected when option list is hardcoded instead of ng-options

### ISSUE THREAD

**Issue by coreycochran89** [Availity/availity-angular#47]

**Comment by coreycochran89** [comment]
current issue occurs in getSelected at the collection property because collection property does not exist without ng-options with current design.

**Comment by robmcguinness** [comment]
@coreycochran89 after further review i'm not sure if this should be supported.  I think functionality would be better served by creating a service/factory/constant/value function that supplies data to the directive so that:
 
* data can be shared if needed
* data can be tested easier

let me know your thoughts.
